---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nfs_provisioner
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.nfs_provisioner
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.storage.nfs_provisioner
      dest:
        path: .values.images.tags
data:
  chart_name: nfs-provisioner
  release: nfs-provisioner
  namespace: kube-system
  protected:
    continue_processing: false
  wait:
    timeout: 900
    labels:
      release_group: airship-nfs-provisioner
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-nfs-provisioner
  values:
    labels:
      nfs:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
    storage:
      hostPath:
        path: /var/lib/airship/nfs
      persistentVolumeClaim:
        size: '30Gi'
    storageclass:
      name: general
  dependencies:
    - nfs_htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nfs_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.nfs_htk
      dest:
        path: .source
data:
  chart_name: nfs_htk
  release: nfs_htk
  namespace: nfs_htk
  values: {}
  dependencies: []
...
