---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-promenade
  replacement: true
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: ucp-promenade
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    # HTTP Proxy env
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .proxy.http
      dest:
        path: .values.pod.env.promenade_api[0].value
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .proxy.https
      dest:
        path: .values.pod.env.promenade_api[1].value
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .proxy.no_proxy
      dest:
        path: .values.pod.env.promenade_api[2].value
data:
  values:
    pod:
      env:
        promenade_api:
          - name: http_proxy
          - name: https_proxy
          - name: no_proxy
...
